### ISSUE TITLE
outdated/changed package?

### ISSUE THREAD

**Issue by joeljosephjin** [montrealrobotics/La-MAML#1]
https://github.com/montrealrobotics/La-MAML/blob/e707a7842585189356da280e00f1158350aff27c/environment.yml#L283

'chamfer' package does not exist in pip or conda.

but 'chamferdist' does exist. https://pypi.org/project/chamferdist/

can you clarify?

cheers!

**Comment by gunshi** [comment]
Hey @joeljosephjin, @ykarmesh  updated the repo with a more minimal env config (since we didn't need many of the included packages like chamfer), could you try again and let us know if that works for you?

**Comment by joeljosephjin** [comment]
@gunshi yes it works. thanks!
